import type { Destination } from "@/types";

// This file stands in for a Supabase query layer. Once the database from
// Phase 1's schema (see /supabase/schema.sql) is connected, replace the
// array below with a `getDestinations()` query against the `destinations`
// table and keep the same return shape so components don't need to change.

export const seedDestinations: Destination[] = [
  {
    id: "kenya",
    slug: "kenya",
    countryName: "Kenya",
    flagEmoji: "🇰🇪",
    heroImage: "https://picsum.photos/seed/kenya-hero/1200/800",
    shortDescription:
      "Big-five safaris, the Maasai Mara, and Nairobi's vibrant food and city culture.",
    overview:
      "Kenya is the heartbeat of East African safari travel, home to the Maasai Mara's great wildebeest migration and a Nairobi food scene that rewards the curious traveler.",
    bestTimeToVisit: "July to October for the wildebeest migration.",
    visaInfo: "eVisa required for most nationalities, apply online before travel.",
    isLaunchDestination: true,
    metaTitle: "Kenya Safari Tours & Travel Guide | Teyezilla Expeditions",
    metaDescription:
      "Plan your Kenya safari with Teyezilla Expeditions: Maasai Mara, Amboseli, Nairobi city and food tours, and more.",
    ogImage: "https://picsum.photos/seed/kenya-og/1200/800",
  },
  {
    id: "tanzania",
    slug: "tanzania",
    countryName: "Tanzania",
    flagEmoji: "🇹🇿",
    heroImage: "https://picsum.photos/seed/tanzania-hero/1200/800",
    shortDescription:
      "The Serengeti, Ngorongoro Crater, and the roof of Africa at Kilimanjaro.",
    overview:
      "Tanzania pairs the endless plains of the Serengeti with the natural amphitheater of Ngorongoro Crater and the challenge of Kilimanjaro.",
    bestTimeToVisit: "June to October, dry season.",
    visaInfo: "eVisa available online for most nationalities.",
    isLaunchDestination: true,
    metaTitle: "Tanzania Safari Tours | Serengeti & Kilimanjaro | Teyezilla",
    metaDescription:
      "Serengeti safaris, Ngorongoro Crater tours, and Kilimanjaro treks with Teyezilla Expeditions.",
    ogImage: "https://picsum.photos/seed/tanzania-og/1200/800",
  },
  {
    id: "zanzibar",
    slug: "zanzibar",
    countryName: "Zanzibar",
    flagEmoji: "🏝️",
    heroImage: "https://picsum.photos/seed/zanzibar-hero/1200/800",
    shortDescription:
      "White-sand beaches, Stone Town's spice-scented alleys, and Mnemba Island diving.",
    overview:
      "Zanzibar is the beach-and-culture pairing at the end of a mainland safari, with Stone Town's UNESCO old quarter and Mnemba Island's reef diving.",
    bestTimeToVisit: "June to October, and December to February.",
    visaInfo: "Covered under the Tanzania eVisa.",
    isLaunchDestination: true,
    metaTitle: "Zanzibar Beach Holidays & Stone Town Tours | Teyezilla",
    metaDescription:
      "Zanzibar beach escapes, Stone Town tours, and Mnemba Island experiences with Teyezilla Expeditions.",
    ogImage: "https://picsum.photos/seed/zanzibar-og/1200/800",
  },
  {
    id: "egypt",
    slug: "egypt",
    countryName: "Egypt",
    flagEmoji: "🇪🇬",
    heroImage: "https://picsum.photos/seed/egypt-hero/1200/800",
    shortDescription:
      "The Pyramids of Giza, Nile cruises, and the temples of Luxor.",
    overview:
      "Egypt's ancient wonders span the Pyramids of Giza, the temple-lined banks of Luxor, and multi-day Nile cruises between them.",
    bestTimeToVisit: "October to April, outside peak summer heat.",
    visaInfo: "eVisa or visa on arrival for most nationalities.",
    isLaunchDestination: true,
    metaTitle: "Egypt Tours: Pyramids, Nile Cruises & Luxor | Teyezilla",
    metaDescription:
      "Pyramids of Giza tours, Nile cruises, and Luxor temple visits with Teyezilla Expeditions.",
    ogImage: "https://picsum.photos/seed/egypt-og/1200/800",
  },
  {
    id: "morocco",
    slug: "morocco",
    countryName: "Morocco",
    flagEmoji: "🇲🇦",
    heroImage: "https://picsum.photos/seed/morocco-hero/1200/800",
    shortDescription:
      "Marrakech's souks, the blue city of Chefchaouen, and Sahara desert camps.",
    overview:
      "Morocco moves from Marrakech's medina to the blue-washed streets of Chefchaouen and out into Sahara desert camps under open sky.",
    bestTimeToVisit: "March to May, and September to November.",
    visaInfo: "Visa-free for many nationalities for stays under 90 days.",
    isLaunchDestination: true,
    metaTitle: "Morocco Desert Tours: Marrakech, Chefchaouen & Sahara | Teyezilla",
    metaDescription:
      "Marrakech city tours, Chefchaouen day trips, and Sahara desert camps with Teyezilla Expeditions.",
    ogImage: "https://picsum.photos/seed/morocco-og/1200/800",
  },
  {
    id: "rwanda",
    slug: "rwanda",
    countryName: "Rwanda",
    flagEmoji: "🇷🇼",
    heroImage: "https://picsum.photos/seed/rwanda-hero/1200/800",
    shortDescription: "Mountain gorilla trekking in the Virunga highlands.",
    overview: "Coming soon to Teyezilla Expeditions.",
    bestTimeToVisit: "June to September.",
    visaInfo: "eVisa available online.",
    isLaunchDestination: false,
    metaTitle: "Rwanda Gorilla Trekking Tours | Teyezilla Expeditions",
    metaDescription: "Mountain gorilla trekking tours in Rwanda, coming soon to Teyezilla Expeditions.",
    ogImage: "https://picsum.photos/seed/rwanda-og/1200/800",
  },
  {
    id: "uganda",
    slug: "uganda",
    countryName: "Uganda",
    flagEmoji: "🇺🇬",
    heroImage: "https://picsum.photos/seed/uganda-hero/1200/800",
    shortDescription: "The Pearl of Africa: gorillas, chimps, and the source of the Nile.",
    overview: "Coming soon to Teyezilla Expeditions.",
    bestTimeToVisit: "December to February, and June to August.",
    visaInfo: "eVisa available online.",
    isLaunchDestination: false,
    metaTitle: "Uganda Safari & Gorilla Tours | Teyezilla Expeditions",
    metaDescription: "Uganda safaris and gorilla trekking, coming soon to Teyezilla Expeditions.",
    ogImage: "https://picsum.photos/seed/uganda-og/1200/800",
  },
  {
    id: "south-africa",
    slug: "south-africa",
    countryName: "South Africa",
    flagEmoji: "🇿🇦",
    heroImage: "https://picsum.photos/seed/south-africa-hero/1200/800",
    shortDescription: "Cape Town, the Garden Route, and Kruger safaris.",
    overview: "Coming soon to Teyezilla Expeditions.",
    bestTimeToVisit: "May to September for safari.",
    visaInfo: "Visa-free for many nationalities for short stays.",
    isLaunchDestination: false,
    metaTitle: "South Africa Safari & Cape Town Tours | Teyezilla Expeditions",
    metaDescription: "South Africa safaris and Cape Town tours, coming soon to Teyezilla Expeditions.",
    ogImage: "https://picsum.photos/seed/south-africa-og/1200/800",
  },
  {
    id: "botswana",
    slug: "botswana",
    countryName: "Botswana",
    flagEmoji: "🇧🇼",
    heroImage: "https://picsum.photos/seed/botswana-hero/1200/800",
    shortDescription: "The Okavango Delta and exclusive low-impact safaris.",
    overview: "Coming soon to Teyezilla Expeditions.",
    bestTimeToVisit: "May to October.",
    visaInfo: "Visa-free for many nationalities for short stays.",
    isLaunchDestination: false,
    metaTitle: "Botswana Okavango Delta Safaris | Teyezilla Expeditions",
    metaDescription: "Okavango Delta safaris in Botswana, coming soon to Teyezilla Expeditions.",
    ogImage: "https://picsum.photos/seed/botswana-og/1200/800",
  },
  {
    id: "zambia",
    slug: "zambia",
    countryName: "Zambia",
    flagEmoji: "🇿🇲",
    heroImage: "https://picsum.photos/seed/zambia-hero/1200/800",
    shortDescription: "Victoria Falls and walking safaris in South Luangwa.",
    overview: "Coming soon to Teyezilla Expeditions.",
    bestTimeToVisit: "May to October.",
    visaInfo: "eVisa available online.",
    isLaunchDestination: false,
    metaTitle: "Zambia Safari & Victoria Falls Tours | Teyezilla Expeditions",
    metaDescription: "Zambia walking safaris and Victoria Falls tours, coming soon to Teyezilla Expeditions.",
    ogImage: "https://picsum.photos/seed/zambia-og/1200/800",
  },
  {
    id: "zimbabwe",
    slug: "zimbabwe",
    countryName: "Zimbabwe",
    flagEmoji: "🇿🇼",
    heroImage: "https://picsum.photos/seed/zimbabwe-hero/1200/800",
    shortDescription: "Victoria Falls, Hwange National Park, and Great Zimbabwe.",
    overview: "Coming soon to Teyezilla Expeditions.",
    bestTimeToVisit: "May to October.",
    visaInfo: "eVisa available online.",
    isLaunchDestination: false,
    metaTitle: "Zimbabwe Safari Tours | Teyezilla Expeditions",
    metaDescription: "Zimbabwe safaris and Victoria Falls tours, coming soon to Teyezilla Expeditions.",
    ogImage: "https://picsum.photos/seed/zimbabwe-og/1200/800",
  },
];


